### ISSUE TITLE
? Bug: "TypeError: inputStr() got an unexpected keyword argument 'validationFunc'"

### ISSUE THREAD

**Issue by andydoc** [asweigart/pyinputplus#27]
With thefollowing code, on windows 10, using IDLE, both in scripts and in console, I get the above error:
```
def path_valid(input_string):
    if os.path.exists(input_string) and input_string.endswith("terminal64.exe"):
        return
    else:
        raise ValueError("Terminal not found at location: '{}'".format(input_string))
    
inp_path = "C:/Program Files/FTMO MetaTrader 5/terminal64.exe"
input_string = pyip.inputStr(prompt="Where is terminal? Default = {}".format(inp_path),\
                         default=inp_path, timeout=10, blank = True, validationFunc = path_valid)
if not input_string == '':
    inp_path = input_string
print("Confirmed: MT5 terminal path = ", inp_path)
```
Not sure what is going wrong: any ideas

**Comment by andydoc** [comment]
Simplifying the original function call down into 3 * 1-step lines gives the same error:
```
prompt = "Where is terminal? Default = {}".format(inp_path)
d = {'prompt': prompt, 'default': inp_path, 'timeout': 10, 'blank': True, 'validationFunc': path_valid}
input_string = pyip.inputStr(**d)
```
giving:

> Traceback (most recent call last):
> &nbsp;&nbsp;File "C:/Users/andyd/Desktop/dev/w-h4 data.py", line 23, in \<module\>
> &nbsp;&nbsp;&nbsp;&nbsp;input_string = pyip.inputStr(**d)
> TypeError: inputStr() got an unexpected keyword argument 'validationFunc'

**Comment by mpettis** [comment]
Came across this for a related problem.  The 'validationFunc' argument was removed from the interface, so you can't use it.  I don't know why, seemed very useful.  Was looking for when that happened.  Scroll to the bottom of this, and you'll see that argument is no longer a choice... https://pyinputplus.readthedocs.io/en/latest/

**Comment by andydoc** [comment]
Thanks - my usual problem - RTM

**Comment by mpettis** [comment]
> Thanks - my usual problem - RTM

Don't beat yourself up -- there's some conflicting documentation out there, took some work to track down.
