### ISSUE TITLE
module 'pysimplevalidate' has no attribute 'validateIp'

### ISSUE THREAD

**Issue by severindellsperger** [asweigart/pyinputplus#9]
Hi @asweigart, Hi @all,
Every time we'd like to use the function `inputIp()` we got the following error:
`module 'pysimplevalidate' has no attribute 'validateIp'`

I wrote a simple script to demonstrate it:

```python
import pyinputplus as pyip
dns_server= pyip.inputIp(prompt="Enter your DNS Server: ")
print(f"Your DNS server is set to {dns_server}")
```

When I execute the program above I have the following output:

```bash
Enter your DNS Server: 10.10.10.10
module 'pysimplevalidate' has no attribute 'validateIp'
Enter your DNS Server: 
```

I checked the `pysimplevalidate` module and the function `validateIp` is called `validateIP`. There is a little typo in the code which has to be changed.

Kind 
Severin

**Comment by asweigart** [comment]
Fixed in pysimplevalidate 0.2.11

Thanks!
